#ifndef TSMS_DEF_H
#define TSMS_DEF_H

typedef uint32_t TSMS_CLOCK_FREQUENCY;

typedef enum{
	TSMS_TRANSFER_MSB = 0U, TSMS_TRANSFER_LSB
} TSMS_TRANSFER_TYPE;

typedef enum {
	TSMS_REGISTER_MSB = 0, TSMS_REGISTER_LSB
} TSMS_REGISTER_DATA_TYPE;

typedef enum {
	TSMS_8BIT = 0, TSMS_16BIT, TSMS_24BIT, TSMS_32BIT
} TSMS_BITS;

#endif //TSMS_DEF_H
