#ifndef TSMS_FLOAT_LINK_LIST_H
#define TSMS_FLOAT_LINK_LIST_H

typedef struct TSMS_FLOAT_LINK_LIST *TSMS_FLOAT_LINK_LIST_POINTER;
typedef TSMS_FLOAT_LINK_LIST_POINTER TSMS_FLKLP;

typedef struct TSMS_FLOAT_LINK_NODE *TSMS_FLOAT_LINK_NODE_POINTER;
typedef TSMS_FLOAT_LINK_NODE_POINTER TSMS_FLKNP;

#include "tsms_def.h"

struct TSMS_FLOAT_LINK_NODE {
	float element;
	TSMS_FLKNP next;
	TSMS_FLKNP prev;
};

struct TSMS_FLOAT_LINK_LIST {
	TSMS_FLKNP head;
	TSMS_FLKNP tail;
	TSMS_SIZE length;
};

TSMS_FLKLP TSMS_FLOAT_LINK_LIST_create();

TSMS_RESULT TSMS_FLOAT_LINK_LIST_add(TSMS_FLKLP list, float element);

TSMS_RESULT TSMS_FLOAT_LINK_LIST_remove(TSMS_FLKLP list, TSMS_POS index);

TSMS_POS TSMS_FLOAT_LINK_LIST_removeElement(TSMS_FLKLP list, float element);

TSMS_RESULT TSMS_FLOAT_LINK_LIST_release(TSMS_FLKLP list);

TSMS_RESULT TSMS_FLOAT_LINK_LIST_clear(TSMS_FLKLP list);

TSMS_RESULT TSMS_FLOAT_LINK_LIST_insert(TSMS_FLKLP list, float element, TSMS_POS index);

TSMS_RESULT TSMS_FLOAT_LINK_LIST_deleteNode(TSMS_FLKLP list, TSMS_FLKNP node);


#endif //TSMS_FLOAT_LINK_LIST_H
