#ifndef TSMS_INT_LINK_LIST_H
#define TSMS_INT_LINK_LIST_H

typedef struct TSMS_INT_LINK_LIST *TSMS_INT_LINK_LIST_POINTER;
typedef TSMS_INT_LINK_LIST_POINTER TSMS_ILKLP;

typedef struct TSMS_INT_LINK_NODE *TSMS_INT_LINK_NODE_POINTER;
typedef TSMS_INT_LINK_NODE_POINTER TSMS_ILKNP;

#include "tsms_def.h"

struct TSMS_INT_LINK_NODE {
	int element;
	TSMS_ILKNP next;
	TSMS_ILKNP prev;
};

struct TSMS_INT_LINK_LIST {
	TSMS_ILKNP head;
	TSMS_ILKNP tail;
	TSMS_SIZE length;
};

TSMS_ILKLP TSMS_INT_LINK_LIST_create();

TSMS_RESULT TSMS_INT_LINK_LIST_add(TSMS_ILKLP list, int element);

TSMS_RESULT TSMS_INT_LINK_LIST_remove(TSMS_ILKLP list, TSMS_POS index);

TSMS_POS TSMS_INT_LINK_LIST_removeElement(TSMS_ILKLP list, int element);

TSMS_RESULT TSMS_INT_LINK_LIST_release(TSMS_ILKLP list);

TSMS_RESULT TSMS_INT_LINK_LIST_clear(TSMS_ILKLP list);

TSMS_RESULT TSMS_INT_LINK_LIST_insert(TSMS_ILKLP list, int element, TSMS_POS index);

TSMS_RESULT TSMS_INT_LINK_LIST_deleteNode(TSMS_ILKLP list, TSMS_ILKNP node);

#endif //TSMS_INT_LINK_LIST_H
