#ifndef TSMS_GPIO_H
#define TSMS_GPIO_H

#define TSMS_NULL_GHP (TSMS_GHP)TSMS_NULL

typedef enum {
	TSMS_GPIO_STATUS_LOW = 0, TSMS_GPIO_STATUS_HIGH, TSMS_GPIO_STATUS_ERROR
} TSMS_GPIO_STATUS;

typedef enum {
	TSMS_GPIO_MODE_OUTPUT_OPEN_DRAIN = 0, TSMS_GPIO_MODE_OUTPUT_OD = 0, TSMS_GPIO_MODE_OUTPUT_PULL_PUSH = 1, TSMS_GPIO_MODE_OUTPUT_PP = 1,
	TSMS_GPIO_MODE_INPUT,
	TSMS_GPIO_MODE_IT_RISING, TSMS_GPIO_MODE_IT_FALLING, TSMS_GPIO_IT_MODE_RISING_FALLING
} TSMS_GPIO_MODE;

typedef enum {
	TSMS_GPIO_PULL_UP = 0, TSMS_GPIO_PULL_DOWN, TSMS_GPIO_PULL_NONE
} TSMS_GPIO_PULL;

typedef struct TSMS_GPIO_HANDLER *TSMS_GPIO_HANDLER_POINTER;
typedef TSMS_GPIO_HANDLER_POINTER TSMS_GHP;

typedef struct TSMS_GPIO_HANDLER *TSMS_GPIO_HANDLER_POINTER;
typedef TSMS_GPIO_HANDLER_POINTER TSMS_GHP;

typedef void(*TSMS_IT_GPIO_CALLBACK)(void *, TSMS_GHP);

#include "tsms.h"

TSMS_RESULT TSMS_IT_addGPIO(TSMS_GHP gpio, TSMS_IT_GPIO_CALLBACK callback, void *);

struct TSMS_GPIO_HANDLER {
#ifdef TSMS_STM32_GPIO
	GPIO_TypeDef * port;
	uint16_t pin;
#endif
};

#ifdef TSMS_STM32_GPIO

TSMS_GHP TSMS_GPIO_createHandler(GPIO_TypeDef * port, uint16_t pin);

#endif

TSMS_RESULT TSMS_GPIO_write(TSMS_GHP gpio, TSMS_GPIO_STATUS status);

TSMS_GPIO_STATUS TSMS_GPIO_read(TSMS_GHP gpio);

TSMS_RESULT TSMS_GPIO_release(TSMS_GHP gpio);

TSMS_RESULT TSMS_GPIO_setMode(TSMS_GHP gpio, TSMS_GPIO_MODE mode, TSMS_GPIO_PULL pull);

#endif //TSMS_GPIO_H
