#ifndef TSMS_INT_LINK_LIST_H
#define TSMS_INT_LINK_LIST_H

#include "tsms_def.h"

struct TSMS_INT_LINK_NODE {
	int element;
	TSMS_INT_LKNP next;
	TSMS_INT_LKNP prev;
};

struct TSMS_INT_LINK_LIST {
	TSMS_INT_LKNP head;
	TSMS_INT_LKNP tail;
	TSMS_SIZE length;
};

TSMS_INT_LKLP TSMS_INT_LINK_LIST_create();

TSMS_RESULT TSMS_INT_LINK_LIST_add(TSMS_INT_LKLP list, int element);

TSMS_RESULT TSMS_INT_LINK_LIST_remove(TSMS_INT_LKLP list, TSMS_POS index);

TSMS_POS TSMS_INT_LINK_LIST_removeElement(TSMS_INT_LKLP list, int element);

TSMS_RESULT TSMS_INT_LINK_LIST_release(TSMS_INT_LKLP list);

TSMS_RESULT TSMS_INT_LINK_LIST_clear(TSMS_INT_LKLP list);

TSMS_RESULT TSMS_INT_LINK_LIST_insert(TSMS_INT_LKLP list, int element, TSMS_POS index);

TSMS_RESULT TSMS_INT_LINK_LIST_deleteNode(TSMS_INT_LKLP list, TSMS_INT_LKNP node);

#endif //TSMS_INT_LINK_LIST_H
