#ifndef TSMS_ARRAY_FONT_H
#define TSMS_ARRAY_FONT_H

#define TSMS_FONT_DEFAULT_FONT_WIDTH 7
#define TSMS_FONT_DEFAULT_FONT_HEIGHT 8
#define TSMS_FONT_THICK_FONT_WIDTH 9
#define TSMS_FONT_THICK_FONT_HEIGHT 8
#define TSMS_FONT_HOME_SPUN_FONT_WIDTH 7
#define TSMS_FONT_HOME_SPUN_FONT_HEIGHT 8
#define TSMS_FONT_SEVEN_SEG_FONT_WIDTH 6
#define TSMS_FONT_SEVEN_SEG_FONT_HEIGHT 8
#define TSMS_FONT_WIDE_FONT_WIDTH 10
#define TSMS_FONT_WIDE_FONT_HEIGHT 8
#define TSMS_FONT_TINY_FONT_WIDTH 5
#define TSMS_FONT_TINY_FONT_HEIGHT 8
#define TSMS_FONT_LARGE_FONT_WIDTH 12
#define TSMS_FONT_LARGE_FONT_HEIGHT 16
#define TSMS_FONT_HUGE_FONT_WIDTH 16
#define TSMS_FONT_HUGE_FONT_HEIGHT 24
#define TSMS_FONT_MEGA_FONT_WIDTH 16
#define TSMS_FONT_MEGA_FONT_HEIGHT 32

#include "tsms_def.h"

extern const unsigned char TSMS_FONT_DEFAULT_FONT[94][7];
extern const unsigned char TSMS_FONT_THICK_FONT[59][9];
extern const unsigned char TSMS_FONT_HOME_SPUN_FONT[95][7];
extern const unsigned char TSMS_FONT_SEVEN_SEG_FONT[92][6];
extern const unsigned char TSMS_FONT_WIDE_FONT[59][10];
extern const unsigned char TSMS_FONT_TINY_FONT[95][5];
extern const uint16_t TSMS_FONT_LARGE_FONT[59][12];
extern const uint32_t TSMS_FONT_HUGE_FONT[13][16];
extern const uint32_t TSMS_FONT_MEGA_FONT[13][16];

#endif	// TSMS_ARRAY_FONT_H